spring:
  application:
    name: backend
    jwt:
      secret: ${JWT_SECRET}
      expiration-ms: 86400000 # 24 hours

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        security: DEBUG
    io:
      github:
        devcavin:
          backend:
            security: DEBUG

server:
  port: ${PORT:8080}

app:
  frontend-url: ${FRONTEND_URL}